checkpoint: /app/models/checkpoints/lddm.ckpt
protein: /app/test/kras.pdb
ligand: /app/test/kras_ref_ligand.sdf
output: output/kras_synthesizable
synthesizable: true
seed: 42
sampling_params:
  batch_size: 16
  n_steps: 100
itergen_params:
  max_sampling_iter: 6
  n_samples_per_iter: 64
  filtering_criterion_global: basic_filter
  adaptive_thresholds_global: {}
  fragment_filtering_criterion: basic_filter
  local_filtering_evaluators: [posebusters_local, validity3d_local, clashes_local]
  reference_mols_validity3d: /app/data/validity3d/ligands.sdf
  pb_conf: mol_fast
  pb_conf_local: mol_fast
  filter_results: true
  filtering_criterion_final: filter_results
  reaction_path: /app/data/synspace/reactions.json
  building_blocks_path: /app/data/synspace/building_blocks.pkl
  reaction_to_compound_path: /app/data/synspace/reaction_to_building_blocks.pkl
docking_params:
  use_docking: true
  n_docking_samples_per_iter: 64
  max_selected_docking_samples: 16
  n_sampling_steps: 100
